name: Testing

on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build Code
        run: pwd && whoami && ls -l
      - name: Test
        run: ./test.py  